version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "bundler"]
    groups:
      bundler-version:
        applies-to: version-updates
        patterns:
          - "*"
      bundler-security:
        applies-to: security-updates
        patterns:
          - "*"    

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: ["dependencies", "npm"]
    groups:
      npm-version:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]
    groups:
      github-actions-version:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
