inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
  Exclude:
    - db/schema.rb
    - db/cache_schema.rb
    - db/cable_schema.rb
    - db/queue_schema.rb
