default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", ENV.fetch("USER", "postgres")) %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: <%= ENV.fetch("DB_STATEMENT_TIMEOUT", 5000) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
